services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - default
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - CONNECTION_STRING=postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - default
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - default

networks:
  default:
    driver: bridge