export const mathFunctions = [
  {
    category: "Основные",
    functions: [
      { label: "+", value: " +" },
      { label: "-", value: " -" },
      { label: "×", value: "\\times" },
      { label: "÷", value: "\\frac{}{}" },
      { label: "=", value: " =" },
      { label: "≠", value: "\\neq" },
      { label: "<", value: " <" },
      { label: ">", value: " >" },
      { label: "≤", value: "\\leq" },
      { label: "≥", value: "\\geq" },
    ]
  },
  {
    category: "Алгебра",
    functions: [
      { label: "√", value: "\\sqrt{}" },
      { label: "∛", value: " \\sqrt[3]{} " },
      { label: "x²", value: " x^2" },
      { label: "x³", value: " x^3" },
      { label: "xⁿ", value: " x^{2}" },
      { label: "log", value: "\\log_{}" },
      { label: "ln", value: "\\ln" },
      { label: "e", value: " e" },
      { label: "∑", value: "\\sum_{i=1}^n" },
      { label: "∏", value: "\\prod_{i=1}^n" },
    ]
  },
  {
    category: "Тригонометрия",
    functions: [
      { label: "sin", value: "\\sin" },
      { label: "cos", value: "\\cos" },
      { label: "tan", value: "\\tan" },
      { label: "csc", value: "\\csc" },
      { label: "sec", value: "\\sec" },
      { label: "cot", value: "\\cot" },
      { label: "arcsin", value: "\\arcsin" },
      { label: "arccos", value: "\\arccos" },
      { label: "arctan", value: "\\arctan" },
      { label: "π", value: "\\pi" },
    ]
  },
  {
    category: "Исчисление",
    functions: [
      { label: "∫", value: "\\int" },
      { label: "∬", value: "\\int\\int" },
      { label: "∭", value: "\\int\\int\\int" },
      { label: "∮", value: "\\oint" },
      { label: "∂", value: "\\partial" },
      { label: "lim", value: "\\lim_{x \\to \\infty}" },
      { label: "d/dx", value: "\\frac{d}{dx}" },
      { label: "∇", value: "\\nabla" },
      { label: "∆", value: "\\Delta" },
      { label: "∞", value: "\\infty" },
    ]
  },
  //   Матрицы некорректно работают в MathJax
  // {
  //   category: "Линейная алгебра",
  //   functions: [
  //     { label: "Матрица", value: " \\begin{pmatrix}1 & 1\\\\1 & 1\\end{pmatrix}" },
  //     { label: "Определитель", value: "\\begin{vmatrix} & \\\\ & \\end{vmatrix}" },
  //     { label: "Вектор", value: "\\vec{v}" },
  //     { label: "Скалярное произведение", value: "\\mathbf{a} \\cdot \\mathbf{b}" },
  //     { label: "Векторное произведение", value: "\\mathbf{a} \\times \\mathbf{b}" },
  //     { label: "Транспонирование", value: " A^T" },
  //     { label: "Обратная матрица", value: " A^{-1}" },
  //     { label: "Собственное значение", value: "\\lambda" },
  //     { label: "Собственный вектор", value: "\\vec{v}" },
  //     { label: "Ранг", value: "\\text{rank}(A)" },
  //   ]
  // },
  {
    category: "Греческий алфавит",
    functions: [
      { label: "α", value: "\\alpha" },
      { label: "β", value: "\\beta" },
      { label: "γ", value: "\\gamma" },
      { label: "δ", value: "\\delta" },
      { label: "ε", value: "\\epsilon" },
      { label: "ζ", value: "\\zeta" },
      { label: "η", value: "\\eta" },
      { label: "θ", value: "\\theta" },
      { label: "ι", value: "\\iota" },
      { label: "κ", value: "\\kappa" },
      { label: "λ", value: "\\lambda" },
      { label: "μ", value: "\\mu" },
      { label: "ν", value: "\\nu" },
      { label: "ξ", value: "\\xi" },
      { label: "ο", value: " o" },
      { label: "π", value: "\\pi" },
      { label: "ρ", value: "\\rho" },
      { label: "σ", value: "\\sigma" },
      { label: "τ", value: "\\tau" },
      { label: "υ", value: "\\upsilon" },
      { label: "φ", value: "\\phi" },
      { label: "χ", value: "\\chi" },
      { label: "ψ", value: "\\psi" },
      { label: "ω", value: "\\omega" },
      { label: "Γ", value: "\\Gamma" },
      { label: "Δ", value: "\\Delta" },
      { label: "Θ", value: "\\Theta" },
      { label: "Λ", value: "\\Lambda" },
      { label: "Ξ", value: "\\Xi" },
      { label: "Π", value: "\\Pi" },
      { label: "Σ", value: "\\Sigma" },
      { label: "Υ", value: "\\Upsilon" },
      { label: "Φ", value: "\\Phi" },
      { label: "Ψ", value: "\\Psi" },
      { label: "Ω", value: "\\Omega" },
    ]
  },
  {
    category: "Множества и логика",
    functions: [
      { label: "∈", value: "\\in" },
      { label: "∉", value: "\\notin" },
      { label: "∋", value: "\\ni" },
      { label: "⊂", value: "\\subset" },
      { label: "⊃", value: "\\supset" },
      { label: "⊄", value: "\\not\\subset" },
      { label: "⊅", value: "\\not\\supset" },
      { label: "⊆", value: "\\subseteq" },
      { label: "⊇", value: "\\supseteq" },
      { label: "∩", value: "\\cap" },
      { label: "∪", value: "\\cup" },
      { label: "∅", value: "\\emptyset" },
      { label: "∀", value: "\\forall" },
      { label: "∃", value: "\\exists" },
      { label: "∄", value: "\\nexists" },
      { label: "¬", value: "\\neg" },
      { label: "∧", value: "\\wedge" },
      { label: "∨", value: "\\vee" },
      { label: "⇒", value: "\\Rightarrow" },
      { label: "⇔", value: "\\Leftrightarrow" },
    ]
  },
];

